### ISSUE TITLE
MSVC2015 - internal error

### ISSUE THREAD

**Issue by gvanem** [pothosware/pothos-comms#22]
While compiling `comms/filter/FIRFilter.cpp`, I'm getting this:
```
FIRFilter.cpp(296): fatal error C1001: An internal error has occurred in the compiler.
(compiler file 'f:\dd\vctools\compiler\cxxfe\sl\p1\c\toil.c', line 9058)
To work around this problem, try simplifying or changing the program near the locations listed above.
...
FIRFilter.cpp(208): note: while compiling class template member function 
'void FIRFilter<std::complex<int8_t>,std::complex<int8_t>,std::complex<double>,
std::complex<int16_t>,std::complex<int16_t>>::work(void)'
FIRFilter.cpp(373): note: see reference to class template instantiation 'FIRFilter<std::complex<int8_t>,std::complex<int8_t>,std::complex<double>,
std::complex<int16_t>,std::complex<int16_t>>' being compiled
```

That line is in `FIRFilter::work (void)`:
```
 y[j+n*L] = fromQ<OutType>(y_n);
```

This is for a 32-bit compile with cl v19.00.23506. On Win-10.

**Comment by guruofquality** [comment]
I don't really know whats wrong, looks like a compiler bug. I regularly compile on msvc2015 64-bit so its possible the 32-bit has some bug. Do you have the latest patches installed?

I think that the compiler is having trouble building the 8-bit version. Something about uint8 and the [fixed format templates](https://github.com/pothosware/pothos/blob/master/include/Pothos/Util/QFormat.hpp). So perhaps a temporary fix is to comment out `ifTypeDeclareFactory(int8_t, int16_t);` I'm curious if that at least gets things building again.

**Comment by gvanem** [comment]
cl v 19.00.23506 is the latest AFAICS.

> I'm curious if that at least gets things building again.

If I comment out some `ifTypeDeclareFactory()`, it just errors above that.

**Comment by guruofquality** [comment]
It seems to hate the sizeof(...stuff)*4, it makes the compiler crash and its probably a bug in the compiler. I should also note that I dont think crashing is consistent because I was able to compile before without noticing this, but it crashes consistently in a simple example.

https://github.com/pothosware/pothos/blob/master/include/Pothos/Util/QFormat.hpp#L48
The goal is to get half of the the size of the type in bits for a default fixed point shift, hence the multiply by 4:

* This causes the compiler crash: `const int n = sizeof(typename Fundamental<U>::Type)*4`
* This is a possible work around to get the 4x multiplier:
`const int n = sizeof(typename Fundamental<U>::Type[4])`

Can you give that a test as well? Theres two instances of that line in the QFormat.hpp

Edit: I was not building the master branch. I introduced this issue on master branch. So msvc probably does crash consistently

Edit2: This workaround fixes msvc2013 but not 2015...

**Comment by gvanem** [comment]
> This is for a 32-bit compile with cl v19.00.23506. On Win-10.

I tried with what now to me seems be the latest; cl v19.00.24215.1 (from [Visual Studio Community](https://www.visualstudio.com/downloads/)). This doesn't crash in that file.

While building with that I had to patch somewhere else:
```diff
--- a/Pothos/serialization/impl/config/compiler/visualc.hpp 2016-01-09 21:52:01
+++ b/Pothos/serialization/impl/config/compiler/visualc.hpp 2016-12-31 03:00:03
@@ -257,6 +257,8 @@
 #     define POTHOS_COMPILER_VERSION 11.0
 #   elif _MSC_VER < 1900
 #     define POTHOS_COMPILER_VERSION 12.0
+#   elif _MSC_VER < 2000
+#     define POTHOS_COMPILER_VERSION 14.0
 #   else
 #     define POTHOS_COMPILER_VERSION _MSC_VER
 #   endif
@@ -266,8 +268,8 @@
 #endif

 //
-// last known and checked version is 18.00.20827.3 (VC12 RC, aka 2013 RC):
-#if (_MSC_VER > 1800 && _MSC_FULL_VER > 180020827)
+// last known and checked version is 19.00.24215.1 (VC14 RC, aka 2015):
+#if (_MSC_VER > 1900 && _MSC_FULL_VER > 1900242151)
 #  if defined(POTHOS_ASSERT_CONFIG)
 #     error "Unknown compiler version - please run the configure tests and report the results"
 #  else
```

So while v19.00.24215.1 seems to work for far, but v19.00.23506 doesn't, you might need to make a *hole* in those `ifdef` tests?

**Comment by guruofquality** [comment]
Fixed on master: https://github.com/pothosware/pothos/commit/b6bbfb657813dca87ee36fe671ac6baa2df2c1fc

**Comment by guruofquality** [comment]
> While building with that I had to patch somewhere else:

I never had any errors with this code on vc14, but I am about to remove this dependency entirely: https://github.com/pothosware/pothos/pull/108
